### ISSUE TITLE
qrcode stuff implementation problem

### ISSUE THREAD

**Issue by Allan-Nava** [piis3/smorku#1]
I have copied your qrcode stuff but I have problem

**Comment by piis3** [comment]
What's the problem?

**Comment by Allan-Nava** [comment]
I cannot use it, i'm trying to implement it in source folder

**Comment by piis3** [comment]
It's implemented as a scenegraph component, it would probably require some refactoring to work outside of scenegraph. It's been a while since I wrote anything for the roku world so I'm not sure what's involved there. Have you tried using it as a scenegraph component?

**Comment by Allan-Nava** [comment]
> It's implemented as a scenegraph component, it would probably require some refactoring to work outside of scenegraph. It's been a while since I wrote anything for the roku world so I'm not sure what's involved there. Have you tried using it as a scenegraph component?

It doesn't work inside components

**Comment by piis3** [comment]
Can you please be specific about the problem you're seeing and provide any error messages, or logs and an example of what you're trying to do?

**Comment by Allan-Nava** [comment]
Problem with the some functions with **mod** for example

**Comment by piis3** [comment]
Again, please include error messages or logs. It's hard to help if all I know is that there is a problem.
